package app.fukaha.web

import app.fukaha.AppLanguage
import kotlinx.browser.window

/**
 * Web copy. Wording is lifted from the Android `values/strings.xml` and `values-ar/strings.xml`
 * so the PWA reads like the app; web-only lines follow the same formal MSA voice in Arabic.
 *
 * Named constructor arguments give compile-time parity between the two locales, which is
 * why this is a class of fields rather than a map.
 */
class Strings(
    val appName: String,
    val settings: String,
    val about: String,
    val back: String,
    val copied: String,
    val copyFailed: String,
    val noLink: String,
    val preparing: String,
    val shareSheetSubtitle: String,
    val unknownPlatform: String,
    val originalPreview: String,
    val cleanedPreview: String,
    val embedPreview: String,
    val actionCopyShort: String,
    val actionShareShort: String,
    val openLink: String,
    val pasteTitle: String,
    val pasteHint: String,
    val pastePlaceholder: String,
    val pasteFromClipboard: String,
    val pasteClear: String,
    val pasteOpen: String,
    val pasteInvalid: String,
    val pasteSample: String,
    val clipboardEmpty: String,
    val clipboardDenied: String,
    val clipboardFailed: String,
    val clipboardInsecure: String,
    val cleanLinkCopied: String,
    val embedLinkCopied: String,
    val homePrepareFailed: String,
    val homeCopyFailed: String,
    val defaultActionHint: String,
    val actionAsk: String,
    val actionAskHint: String,
    val actionClean: String,
    val actionCleanHint: String,
    val actionEmbed: String,
    val actionEmbedHint: String,
    val language: String,
    val languageSystem: String,
    val languageEnglish: String,
    val languageArabic: String,
    val languageJapanese: String,
    val languageSimplifiedChinese: String,
    val languageSpanish: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val preferredFixers: String,
    val preferredFixerUnknown: String,
    val fixerInUse: String,
    val selected: String,
    val fixerYourPick: String,
    val fixerCatalogDefault: String,
    val fixerChooseTitle: String,
    val sectionSharing: String,
    val installTitle: String,
    val installBody: String,
    val installAction: String,
    val installedNote: String,
    val iosInstallHint: String,
    val shareSheetUnsupported: String,
    val notInstallableHint: String,
    val openInBrowserTitle: String,
    val openInBrowserBody: String,
    val openInBrowserAction: String,
    val webLimitsTitle: String,
    val shortLinkNote: String,
    val downloadNote: String,
    val androidApp: String,
    val embedHealthTitle: String,
    val embedHealthHint: String,
    val embedHealthRefresh: String,
    val embedHealthNever: String,
    val embedHealthOffline: String,
    val embedHealthBusy: String,
    val embedHealthAlive: String,
    val embedHealthDead: String,
    val embedUnreachable: String,
    val aboutBody: String,
    val version: String,
    val githubTitle: String,
    val githubSubtitle: String,
    val donate: String,
    val donateSubtitle: String,
    val creditsTitle: String,
    val credits: String,
    val developerTitle: String,
    val developerSite: String,
    private val fixerByAuthorFormat: String,
    private val fixerPickSubtitleFormat: String,
    private val fixerStandInFormat: String,
    private val embedHealthCountsFormat: String,
    private val embedHealthProgressFormat: String,
    private val embedHealthCooldownFormat: String,
) {
    fun fixerByAuthor(author: String): String = fixerByAuthorFormat.replace("%s", author)

    fun fixerPickSubtitle(platform: String): String = fixerPickSubtitleFormat.replace("%s", platform)

    fun fixerStandIn(picked: String): String = fixerStandInFormat.replace("%name", picked)

    fun embedHealthCounts(alive: Int, dead: Int): String = embedHealthCountsFormat
        .replace("%alive", alive.toString())
        .replace("%dead", dead.toString())

    fun embedHealthProgress(done: Int, total: Int): String = embedHealthProgressFormat
        .replace("%done", done.toString())
        .replace("%total", total.toString())

    fun embedHealthCooldownToast(minutes: Int): String =
        embedHealthCooldownFormat.replace("%min", minutes.toString())

    companion object {
        val EN = Strings(
            appName = "Fukaha",
            settings = "Settings",
            about = "About",
            back = "Back",
            copied = "Copied",
            copyFailed = "Could not copy, select the link instead",
            noLink = "No link found in shared text",
            preparing = "Preparing…",
            shareSheetSubtitle = "Clean it or fix the preview — then share again",
            unknownPlatform = "Unknown",
            originalPreview = "Original link",
            cleanedPreview = "Cleaned link",
            embedPreview = "Embed link",
            actionCopyShort = "Copy",
            actionShareShort = "Share",
            openLink = "Open link",
            pasteTitle = "Paste a link",
            pasteHint = "Clean it or fix the preview, then share it again.",
            pastePlaceholder = "https://x.com/…",
            pasteFromClipboard = "Paste from clipboard",
            pasteClear = "Clear link",
            pasteOpen = "Open share screen",
            pasteInvalid = "That does not look like a link yet",
            pasteSample = "Try a sample link",
            clipboardEmpty = "Your clipboard is empty",
            clipboardDenied = "Your browser blocked clipboard access. Allow it for this site, " +
                "or paste into the field yourself.",
            clipboardFailed = "Could not read the clipboard, paste into the field instead",
            clipboardInsecure = "Browsers block clipboard access on local HTTP addresses. " +
                "Paste into the field yourself.",
            cleanLinkCopied = "Clean link copied",
            embedLinkCopied = "Embed link copied",
            homePrepareFailed = "Could not prepare this link. Check it and try again.",
            homeCopyFailed = "Could not copy the link. Allow clipboard access and try again.",
            defaultActionHint = "What Fukaha should do when you share a link into it",
            actionAsk = "Ask each time",
            actionAskHint = "Show the options and let you choose",
            actionClean = "Clean link",
            actionCleanHint = "Copy the cleaned URL immediately",
            actionEmbed = "Embed link",
            actionEmbedHint = "Copy the embed-friendly URL immediately",
            language = "Language",
            languageSystem = "System",
            languageEnglish = "English",
            languageArabic = "العربية",
            languageJapanese = "日本語",
            languageSimplifiedChinese = "简体中文",
            languageSpanish = "Español",
            theme = "Theme",
            themeSystem = "System",
            themeLight = "Light",
            themeDark = "Dark",
            preferredFixers = "Preferred embed fixers",
            preferredFixerUnknown = "No fixer selected",
            fixerInUse = "In use",
            selected = "Selected",
            fixerYourPick = "Your pick",
            fixerCatalogDefault = "Default",
            fixerChooseTitle = "Choose embed fixer",
            sectionSharing = "Sharing",
            installTitle = "Add Fukaha to your share sheet",
            installBody = "Install the app, then Fukaha shows up whenever you share a link from another app.",
            installAction = "Install",
            installedNote = "Installed. Share a link from any app and pick Fukaha.",
            iosInstallHint = "On iPhone, open the Share menu in Safari and choose Add to Home Screen. " +
                "iOS does not let web apps join the share sheet, so paste links here instead.",
            shareSheetUnsupported = "The share sheet needs Chrome on Android",
            notInstallableHint = "This browser cannot add Fukaha to the share sheet. " +
                "Chrome on Android can, and pasting works everywhere.",
            openInBrowserTitle = "Open Fukaha in your browser",
            openInBrowserBody = "An in-app browser cannot install apps or open the share menu. " +
                "Open Fukaha in Chrome or Safari instead.",
            openInBrowserAction = "Open in browser",
            webLimitsTitle = "Only in the app",
            shortLinkNote = "Short links are not followed here. Browsers block reading other sites' redirects.",
            downloadNote = "Media download needs the Android or iOS app.",
            androidApp = "Android app",
            embedHealthTitle = "Embedder reachability",
            embedHealthHint = "Contacts each fixer host once from your browser to see which still answer. " +
                "Unreachable ones are skipped when rewriting a link.",
            embedHealthRefresh = "Check embedders",
            embedHealthNever = "Not checked yet",
            embedHealthOffline = "Nothing answered, check your connection",
            embedHealthBusy = "A check is already running",
            embedHealthAlive = "Alive",
            embedHealthDead = "Unreachable",
            embedUnreachable = "Embed link · unreachable",
            aboutBody = "Fukaha (فكها) cleans tracking from social links and rewrites them to " +
                "embed-friendly hosts. Install it to clean links straight from the share menu.",
            version = "Version",
            githubTitle = "GitHub",
            githubSubtitle = "View source and releases",
            donate = "Donate",
            donateSubtitle = "Support the developer on GitHub",
            creditsTitle = "Credits",
            credits = "The embed fixer catalog is assembled from several community collections. " +
                "Thanks to their maintainers and the authors of the listed services.",
            developerTitle = "Developer",
            developerSite = "shenepoy.com",
            fixerByAuthorFormat = "by %s",
            fixerPickSubtitleFormat = "Used when Fukaha rewrites %s links for embeds",
            fixerStandInFormat = "Standing in for %name, which is unreachable",
            embedHealthCountsFormat = "%alive alive · %dead unreachable",
            embedHealthProgressFormat = "Checking %done of %total",
            embedHealthCooldownFormat = "Checked recently, try again in %min min",
        )

        val AR = Strings(
            appName = "فكها",
            settings = "الإعدادات",
            about = "حول",
            back = "رجوع",
            copied = "تم النسخ",
            copyFailed = "تعذّر النسخ، حدّد الرابط ونسخه يدوياً",
            noLink = "عذراً، لم نجد رابطاً في النص المُشارَك",
            preparing = "جاري التجهيز…",
            shareSheetSubtitle = "نظّف الرابط أو جهّز المعاينة — ثم شارك من جديد",
            unknownPlatform = "منصة غير معروفة",
            originalPreview = "الرابط الأصلي",
            cleanedPreview = "الرابط النظيف",
            embedPreview = "رابط المعاينة",
            actionCopyShort = "نسخ",
            actionShareShort = "مشاركة",
            openLink = "افتح الرابط",
            pasteTitle = "الصق رابطاً",
            pasteHint = "نظّفه أو صحّح معاينته، ثم شاركه من جديد.",
            pastePlaceholder = "https://x.com/…",
            pasteFromClipboard = "لصق من الحافظة",
            pasteClear = "إفراغ الحقل",
            pasteOpen = "افتح شاشة المشاركة",
            pasteInvalid = "لا يبدو هذا رابطاً بعد",
            pasteSample = "جرّب رابطاً تجريبياً",
            clipboardEmpty = "الحافظة فارغة",
            clipboardDenied = "منع المتصفح الوصول إلى الحافظة. اسمح به لهذا الموقع، " +
                "أو الصق في الحقل بنفسك.",
            clipboardFailed = "تعذّرت قراءة الحافظة، الصق في الحقل بنفسك",
            clipboardInsecure = "المتصفحات تمنع قراءة الحافظة على عناوين HTTP المحلية. " +
                "الصق في الحقل بنفسك.",
            cleanLinkCopied = "تم نسخ الرابط النظيف",
            embedLinkCopied = "تم نسخ رابط المعاينة",
            homePrepareFailed = "تعذّر تجهيز هذا الرابط. تحقّق منه وحاول مجدداً.",
            homeCopyFailed = "تعذّر نسخ الرابط. اسمح بالوصول إلى الحافظة وحاول مجدداً.",
            defaultActionHint = "ما الذي ينفّذه فكها عند مشاركة رابط إليه؟",
            actionAsk = "اسأل في كل مرة",
            actionAskHint = "يعرض الخيارات لتختار بنفسك",
            actionClean = "رابط نظيف",
            actionCleanHint = "ينسخ الرابط النظيف مباشرة",
            actionEmbed = "رابط معاينة",
            actionEmbedHint = "ينسخ رابط المعاينة مباشرة",
            language = "اللغة",
            languageSystem = "حسب النظام",
            languageEnglish = "English",
            languageArabic = "العربية",
            languageJapanese = "日本語",
            languageSimplifiedChinese = "简体中文",
            languageSpanish = "Español",
            theme = "السمة",
            themeSystem = "حسب النظام",
            themeLight = "فاتح",
            themeDark = "داكن",
            preferredFixers = "خدمات المعاينة المفضّلة",
            preferredFixerUnknown = "لم تُحدَّد خدمة",
            fixerInUse = "قيد الاستخدام",
            selected = "محدّد",
            fixerYourPick = "اختيارك",
            fixerCatalogDefault = "الافتراضية",
            fixerChooseTitle = "اختر خدمة المعاينة",
            sectionSharing = "المشاركة",
            installTitle = "أضف فكها إلى قائمة المشاركة",
            installBody = "ثبّت التطبيق ليظهر فكها عند مشاركة أي رابط من تطبيق آخر.",
            installAction = "تثبيت",
            installedNote = "تم التثبيت. شارك رابطاً من أي تطبيق واختر فكها.",
            iosInstallHint = "على iPhone، افتح قائمة المشاركة في Safari واختر «إضافة إلى الشاشة الرئيسية». " +
                "لا يسمح iOS لتطبيقات الويب بالانضمام إلى قائمة المشاركة، فالصق الروابط هنا.",
            shareSheetUnsupported = "تحتاج قائمة المشاركة إلى Chrome على أندرويد",
            notInstallableHint = "هذا المتصفح لا يستطيع إضافة فكها إلى قائمة المشاركة. " +
                "متصفح Chrome على أندرويد يستطيع ذلك، واللصق يعمل في كل مكان.",
            openInBrowserTitle = "افتح فكها في المتصفح",
            openInBrowserBody = "متصفح التطبيقات الداخلي لا يستطيع تثبيت التطبيقات ولا فتح قائمة المشاركة. " +
                "افتح فكها في Chrome أو Safari.",
            openInBrowserAction = "افتح في المتصفح",
            webLimitsTitle = "في التطبيق فقط",
            shortLinkNote = "لا تُتتبَّع الروابط المختصرة هنا، لأن المتصفح يمنع قراءة تحويلات المواقع الأخرى.",
            downloadNote = "يحتاج تحميل الوسائط إلى تطبيق أندرويد أو iOS.",
            androidApp = "تطبيق أندرويد",
            embedHealthTitle = "توفّر خدمات المعاينة",
            embedHealthHint = "يتّصل بكل مضيف مرة واحدة من متصفحك لمعرفة ما يستجيب منها، " +
                "ويتجاوز غير المتاح عند تحويل الرابط.",
            embedHealthRefresh = "فحص خدمات المعاينة",
            embedHealthNever = "لم يُفحص بعد",
            embedHealthOffline = "لم يستجب أي مضيف، تحقّق من اتصالك",
            embedHealthBusy = "هناك فحص جارٍ بالفعل",
            embedHealthAlive = "يعمل",
            embedHealthDead = "غير متاح",
            embedUnreachable = "رابط المعاينة · غير متاح",
            aboutBody = "فكها يزيل التتبع من روابط التواصل الاجتماعي ويحوّلها إلى مضيفات مناسبة للمعاينة. " +
                "ثبّته لتنظيف الروابط من قائمة المشاركة مباشرة.",
            version = "الإصدار",
            githubTitle = "GitHub",
            githubSubtitle = "عرض المصدر والإصدارات",
            donate = "تبرع",
            donateSubtitle = "ادعم المطوّر عبر GitHub",
            creditsTitle = "شكر وتقدير",
            credits = "قائمة خدمات المعاينة مجمّعة من عدة مجموعات مجتمعية. " +
                "شكراً للقائمين عليها ولمؤلفي الخدمات المدرجة.",
            developerTitle = "المطوّر",
            developerSite = "shenepoy.com",
            fixerByAuthorFormat = "من إعداد %s",
            fixerPickSubtitleFormat = "يستخدمها فكها عند تحويل روابط %s إلى روابط معاينة",
            fixerStandInFormat = "بديلة عن %name لتعذّر الوصول إليه",
            embedHealthCountsFormat = "%alive يعمل · %dead غير متاح",
            embedHealthProgressFormat = "جاري الفحص %done من %total",
            embedHealthCooldownFormat = "تم الفحص قبل قليل، أعد المحاولة بعد %min د",
        )

        val JA = Strings(
            appName = "Fukaha",
            settings = "設定",
            about = "このアプリについて",
            back = "戻る",
            copied = "コピーしました",
            copyFailed = "コピーできませんでした。リンクを選択してコピーしてください",
            noLink = "共有されたテキストにリンクが見つかりません",
            preparing = "準備中…",
            shareSheetSubtitle = "リンクを整理またはプレビューを修正して、もう一度共有",
            unknownPlatform = "不明",
            originalPreview = "元のリンク",
            cleanedPreview = "整理済みリンク",
            embedPreview = "埋め込み用リンク",
            actionCopyShort = "コピー",
            actionShareShort = "共有",
            openLink = "リンクを開く",
            pasteTitle = "リンクを貼り付け",
            pasteHint = "リンクを整理またはプレビューを修正して、もう一度共有します。",
            pastePlaceholder = "https://x.com/…",
            pasteFromClipboard = "クリップボードから貼り付け",
            pasteClear = "リンクを消去",
            pasteOpen = "共有画面を開く",
            pasteInvalid = "まだ有効なリンクではないようです",
            pasteSample = "サンプルリンクを試す",
            clipboardEmpty = "クリップボードは空です",
            clipboardDenied = "ブラウザがクリップボードへのアクセスを拒否しました。このサイトで許可するか、入力欄に直接貼り付けてください。",
            clipboardFailed = "クリップボードを読み取れませんでした。入力欄に直接貼り付けてください",
            clipboardInsecure = "ブラウザはローカルの HTTP アドレスでクリップボードへのアクセスをブロックします。入力欄に直接貼り付けてください。",
            cleanLinkCopied = "整理済みリンクをコピーしました",
            embedLinkCopied = "埋め込み用リンクをコピーしました",
            homePrepareFailed = "このリンクを処理できませんでした。内容を確認して、もう一度お試しください。",
            homeCopyFailed = "リンクをコピーできませんでした。クリップボードへのアクセスを許可して、もう一度お試しください。",
            defaultActionHint = "Fukaha にリンクを共有したときの動作",
            actionAsk = "毎回確認",
            actionAskHint = "選択肢を表示して操作を選ぶ",
            actionClean = "リンクを整理",
            actionCleanHint = "整理した URL をすぐにコピー",
            actionEmbed = "埋め込み用リンク",
            actionEmbedHint = "埋め込みに適した URL をすぐにコピー",
            language = "言語",
            languageSystem = "システム",
            languageEnglish = "English",
            languageArabic = "العربية",
            languageJapanese = "日本語",
            languageSimplifiedChinese = "简体中文",
            languageSpanish = "Español",
            theme = "テーマ",
            themeSystem = "システム",
            themeLight = "ライト",
            themeDark = "ダーク",
            preferredFixers = "優先する埋め込み修正サービス",
            preferredFixerUnknown = "修正サービス未選択",
            fixerInUse = "使用中",
            selected = "選択済み",
            fixerYourPick = "選択したサービス",
            fixerCatalogDefault = "デフォルト",
            fixerChooseTitle = "埋め込み修正サービスを選択",
            sectionSharing = "共有",
            installTitle = "Fukaha を共有メニューに追加",
            installBody = "アプリをインストールすると、ほかのアプリからリンクを共有するときに Fukaha が表示されます。",
            installAction = "インストール",
            installedNote = "インストール済みです。任意のアプリからリンクを共有し、Fukaha を選択してください。",
            iosInstallHint = "iPhone では Safari の共有メニューを開き、「ホーム画面に追加」を選択してください。iOS では Web アプリを共有メニューに追加できないため、ここにリンクを貼り付けてください。",
            shareSheetUnsupported = "共有メニューを使うには Android 版 Chrome が必要です",
            notInstallableHint = "このブラウザでは Fukaha を共有メニューに追加できません。Android 版 Chrome では追加でき、貼り付けはどのブラウザでも利用できます。",
            openInBrowserTitle = "ブラウザで Fukaha を開く",
            openInBrowserBody = "アプリ内ブラウザでは、アプリのインストールや共有メニューの表示ができません。Chrome または Safari で Fukaha を開いてください。",
            openInBrowserAction = "ブラウザで開く",
            webLimitsTitle = "アプリ限定",
            shortLinkNote = "ここでは短縮リンクを追跡しません。ブラウザでは他サイトのリダイレクトを読み取れないためです。",
            downloadNote = "メディアのダウンロードには Android または iOS アプリが必要です。",
            androidApp = "Android アプリ",
            embedHealthTitle = "埋め込みサービスの接続状況",
            embedHealthHint = "ブラウザから各修正サービスのホストに一度接続し、応答するか確認します。リンクの変換時には接続できないサービスを除外します。",
            embedHealthRefresh = "埋め込みサービスを確認",
            embedHealthNever = "未確認",
            embedHealthOffline = "応答がありません。接続を確認してください",
            embedHealthBusy = "確認はすでに実行中です",
            embedHealthAlive = "利用可能",
            embedHealthDead = "接続不可",
            embedUnreachable = "埋め込み用リンク・接続不可",
            aboutBody = "Fukaha（فكها）は、SNS のリンクからトラッキング情報を取り除き、埋め込みに適したホストへ変換します。インストールすると、共有メニューから直接リンクを整理できます。",
            version = "バージョン",
            githubTitle = "GitHub",
            githubSubtitle = "ソースコードとリリースを表示",
            donate = "寄付",
            donateSubtitle = "GitHub で開発者を支援",
            creditsTitle = "クレジット",
            credits = "埋め込み修正サービスのカタログは、複数のコミュニティコレクションを基に作成されています。メンテナーと掲載サービスの作者の皆様に感謝します。",
            developerTitle = "開発者",
            developerSite = "shenepoy.com",
            fixerByAuthorFormat = "作者：%s",
            fixerPickSubtitleFormat = "Fukaha が %s のリンクを埋め込み用に変換するときに使用します",
            fixerStandInFormat = "接続できない %name の代わりに使用",
            embedHealthCountsFormat = "利用可能 %alive・接続不可 %dead",
            embedHealthProgressFormat = "%total 件中 %done 件を確認中",
            embedHealthCooldownFormat = "最近確認済みです。%min 分後にもう一度お試しください",
        )

        val ZH_CN = Strings(
            appName = "Fukaha",
            settings = "设置",
            about = "关于",
            back = "返回",
            copied = "已复制",
            copyFailed = "无法复制，请选择链接后手动复制",
            noLink = "分享的文本中没有找到链接",
            preparing = "正在准备…",
            shareSheetSubtitle = "清理链接或修复预览，然后再次分享",
            unknownPlatform = "未知",
            originalPreview = "原始链接",
            cleanedPreview = "已清理链接",
            embedPreview = "嵌入链接",
            actionCopyShort = "复制",
            actionShareShort = "分享",
            openLink = "打开链接",
            pasteTitle = "粘贴链接",
            pasteHint = "清理链接或修复预览，然后再次分享。",
            pastePlaceholder = "https://x.com/…",
            pasteFromClipboard = "从剪贴板粘贴",
            pasteClear = "清除链接",
            pasteOpen = "打开分享页面",
            pasteInvalid = "这似乎还不是有效链接",
            pasteSample = "试用示例链接",
            clipboardEmpty = "剪贴板为空",
            clipboardDenied = "浏览器阻止了剪贴板访问。请允许此网站访问，或手动粘贴到输入框中。",
            clipboardFailed = "无法读取剪贴板，请手动粘贴到输入框中",
            clipboardInsecure = "浏览器会阻止本地 HTTP 地址访问剪贴板。请手动粘贴到输入框中。",
            cleanLinkCopied = "已复制清理后的链接",
            embedLinkCopied = "已复制嵌入链接",
            homePrepareFailed = "无法处理此链接。请检查后重试。",
            homeCopyFailed = "无法复制链接。请允许剪贴板访问后重试。",
            defaultActionHint = "将链接分享到 Fukaha 时执行的操作",
            actionAsk = "每次询问",
            actionAskHint = "显示选项供你选择",
            actionClean = "清理链接",
            actionCleanHint = "立即复制清理后的 URL",
            actionEmbed = "嵌入链接",
            actionEmbedHint = "立即复制适合嵌入的 URL",
            language = "语言",
            languageSystem = "跟随系统",
            languageEnglish = "English",
            languageArabic = "العربية",
            languageJapanese = "日本語",
            languageSimplifiedChinese = "简体中文",
            languageSpanish = "Español",
            theme = "主题",
            themeSystem = "跟随系统",
            themeLight = "浅色",
            themeDark = "深色",
            preferredFixers = "首选嵌入修复服务",
            preferredFixerUnknown = "未选择修复服务",
            fixerInUse = "使用中",
            selected = "已选择",
            fixerYourPick = "你的选择",
            fixerCatalogDefault = "默认",
            fixerChooseTitle = "选择嵌入修复服务",
            sectionSharing = "分享",
            installTitle = "将 Fukaha 添加到分享菜单",
            installBody = "安装应用后，从其他应用分享链接时即可选择 Fukaha。",
            installAction = "安装",
            installedNote = "已安装。从任意应用分享链接并选择 Fukaha。",
            iosInstallHint = "在 iPhone 上，请打开 Safari 的分享菜单并选择“添加到主屏幕”。iOS 不允许网页应用加入分享菜单，因此请在此处粘贴链接。",
            shareSheetUnsupported = "分享菜单需要 Android 版 Chrome",
            notInstallableHint = "此浏览器无法将 Fukaha 添加到分享菜单。Android 版 Chrome 支持此功能，所有浏览器均可使用粘贴功能。",
            openInBrowserTitle = "在浏览器中打开 Fukaha",
            openInBrowserBody = "应用内浏览器无法安装应用或打开分享菜单。请改用 Chrome 或 Safari 打开 Fukaha。",
            openInBrowserAction = "在浏览器中打开",
            webLimitsTitle = "仅限应用",
            shortLinkNote = "此处不会解析短链接，因为浏览器无法读取其他网站的重定向。",
            downloadNote = "下载媒体需要 Android 或 iOS 应用。",
            androidApp = "Android 应用",
            embedHealthTitle = "嵌入服务可用性",
            embedHealthHint = "从浏览器分别连接一次各修复服务主机，以确认哪些仍可响应。转换链接时会跳过无法连接的服务。",
            embedHealthRefresh = "检查嵌入服务",
            embedHealthNever = "尚未检查",
            embedHealthOffline = "所有服务均未响应，请检查网络连接",
            embedHealthBusy = "检查已在进行中",
            embedHealthAlive = "可用",
            embedHealthDead = "无法连接",
            embedUnreachable = "嵌入链接・无法连接",
            aboutBody = "Fukaha（فكها）可清除社交链接中的跟踪参数，并将其改写为适合嵌入预览的主机。安装后即可直接从分享菜单清理链接。",
            version = "版本",
            githubTitle = "GitHub",
            githubSubtitle = "查看源代码和版本",
            donate = "捐赠",
            donateSubtitle = "在 GitHub 上支持开发者",
            creditsTitle = "致谢",
            credits = "嵌入修复服务目录汇集自多个社区项目。感谢维护者以及所列服务的作者。",
            developerTitle = "开发者",
            developerSite = "shenepoy.com",
            fixerByAuthorFormat = "作者：%s",
            fixerPickSubtitleFormat = "Fukaha 改写 %s 链接以供嵌入时使用",
            fixerStandInFormat = "替代无法连接的 %name",
            embedHealthCountsFormat = "%alive 个可用 · %dead 个无法连接",
            embedHealthProgressFormat = "正在检查第 %done 个，共 %total 个",
            embedHealthCooldownFormat = "最近已检查，请在 %min 分钟后重试",
        )

        val ES = Strings(
            appName = "Fukaha",
            settings = "Ajustes",
            about = "Acerca de",
            back = "Volver",
            copied = "Copiado",
            copyFailed = "No se pudo copiar; selecciona el enlace y cópialo manualmente",
            noLink = "No se encontró ningún enlace en el texto compartido",
            preparing = "Preparando…",
            shareSheetSubtitle = "Límpialo o corrige la vista previa y vuelve a compartirlo",
            unknownPlatform = "Desconocida",
            originalPreview = "Enlace original",
            cleanedPreview = "Enlace limpio",
            embedPreview = "Enlace para insertar",
            actionCopyShort = "Copiar",
            actionShareShort = "Compartir",
            openLink = "Abrir enlace",
            pasteTitle = "Pega un enlace",
            pasteHint = "Límpialo o corrige la vista previa y vuelve a compartirlo.",
            pastePlaceholder = "https://x.com/…",
            pasteFromClipboard = "Pegar desde el portapapeles",
            pasteClear = "Borrar enlace",
            pasteOpen = "Abrir pantalla para compartir",
            pasteInvalid = "Esto todavía no parece un enlace válido",
            pasteSample = "Probar un enlace de ejemplo",
            clipboardEmpty = "El portapapeles está vacío",
            clipboardDenied = "El navegador bloqueó el acceso al portapapeles. Permítelo para este sitio o pega el enlace manualmente en el campo.",
            clipboardFailed = "No se pudo leer el portapapeles; pega el enlace manualmente en el campo",
            clipboardInsecure = "Los navegadores bloquean el acceso al portapapeles en direcciones HTTP locales. Pega el enlace manualmente en el campo.",
            cleanLinkCopied = "Enlace limpio copiado",
            embedLinkCopied = "Enlace para insertar copiado",
            homePrepareFailed = "No se pudo preparar este enlace. Revísalo e inténtalo de nuevo.",
            homeCopyFailed = "No se pudo copiar el enlace. Permite el acceso al portapapeles e inténtalo de nuevo.",
            defaultActionHint = "Qué debe hacer Fukaha cuando compartes un enlace con la aplicación",
            actionAsk = "Preguntar siempre",
            actionAskHint = "Mostrar las opciones para que elijas",
            actionClean = "Limpiar enlace",
            actionCleanHint = "Copiar de inmediato la URL limpia",
            actionEmbed = "Enlace para insertar",
            actionEmbedHint = "Copiar de inmediato la URL optimizada para inserciones",
            language = "Idioma",
            languageSystem = "Sistema",
            languageEnglish = "English",
            languageArabic = "العربية",
            languageJapanese = "日本語",
            languageSimplifiedChinese = "简体中文",
            languageSpanish = "Español",
            theme = "Tema",
            themeSystem = "Sistema",
            themeLight = "Claro",
            themeDark = "Oscuro",
            preferredFixers = "Correctores de inserción preferidos",
            preferredFixerUnknown = "Ningún corrector seleccionado",
            fixerInUse = "En uso",
            selected = "Seleccionado",
            fixerYourPick = "Tu elección",
            fixerCatalogDefault = "Predeterminado",
            fixerChooseTitle = "Elegir corrector de inserción",
            sectionSharing = "Compartir",
            installTitle = "Añade Fukaha al menú Compartir",
            installBody = "Instala la aplicación y Fukaha aparecerá cuando compartas un enlace desde otra aplicación.",
            installAction = "Instalar",
            installedNote = "Instalada. Comparte un enlace desde cualquier aplicación y elige Fukaha.",
            iosInstallHint = "En iPhone, abre el menú Compartir de Safari y elige «Añadir a pantalla de inicio». iOS no permite añadir aplicaciones web al menú Compartir, así que pega aquí los enlaces.",
            shareSheetUnsupported = "El menú Compartir requiere Chrome en Android",
            notInstallableHint = "Este navegador no puede añadir Fukaha al menú Compartir. Chrome en Android sí puede, y puedes pegar enlaces en cualquier navegador.",
            openInBrowserTitle = "Abre Fukaha en el navegador",
            openInBrowserBody = "Los navegadores integrados no pueden instalar aplicaciones ni abrir el menú Compartir. Abre Fukaha en Chrome o Safari.",
            openInBrowserAction = "Abrir en el navegador",
            webLimitsTitle = "Solo en la aplicación",
            shortLinkNote = "Aquí no se siguen enlaces cortos porque los navegadores bloquean la lectura de redirecciones de otros sitios.",
            downloadNote = "Para descargar contenido multimedia necesitas la aplicación para Android o iOS.",
            androidApp = "Aplicación para Android",
            embedHealthTitle = "Disponibilidad de los servicios de inserción",
            embedHealthHint = "Contacta una vez con cada servidor corrector desde el navegador para comprobar cuáles responden. Los que no estén disponibles se omiten al reescribir un enlace.",
            embedHealthRefresh = "Comprobar servicios",
            embedHealthNever = "Aún no se ha comprobado",
            embedHealthOffline = "Ningún servicio respondió; comprueba tu conexión",
            embedHealthBusy = "Ya hay una comprobación en curso",
            embedHealthAlive = "Disponible",
            embedHealthDead = "No disponible",
            embedUnreachable = "Enlace para insertar · no disponible",
            aboutBody = "Fukaha (فكها) elimina el seguimiento de los enlaces sociales y los reescribe con servidores compatibles con vistas previas. Instálala para limpiar enlaces directamente desde el menú Compartir.",
            version = "Versión",
            githubTitle = "GitHub",
            githubSubtitle = "Ver el código fuente y las versiones",
            donate = "Donar",
            donateSubtitle = "Apoya al desarrollador en GitHub",
            creditsTitle = "Créditos",
            credits = "El catálogo de correctores de inserción reúne varias colecciones de la comunidad. Gracias a quienes las mantienen y a los autores de los servicios incluidos.",
            developerTitle = "Desarrollador",
            developerSite = "shenepoy.com",
            fixerByAuthorFormat = "por %s",
            fixerPickSubtitleFormat = "Se usa cuando Fukaha reescribe enlaces de %s para insertarlos",
            fixerStandInFormat = "Sustituye a %name, que no está disponible",
            embedHealthCountsFormat = "%alive disponibles · %dead no disponibles",
            embedHealthProgressFormat = "Comprobando %done de %total",
            embedHealthCooldownFormat = "Comprobado hace poco; inténtalo de nuevo en %min min",
        )

        fun resolveLanguage(language: AppLanguage): AppLanguage = when (language) {
            AppLanguage.System -> systemLanguage()
            else -> language
        }

        fun forLanguage(language: AppLanguage): Strings = when (resolveLanguage(language)) {
            AppLanguage.System -> EN
            AppLanguage.English -> EN
            AppLanguage.Arabic -> AR
            AppLanguage.Japanese -> JA
            AppLanguage.SimplifiedChinese -> ZH_CN
            AppLanguage.Spanish -> ES
        }

        fun languageTag(language: AppLanguage): String = when (resolveLanguage(language)) {
            AppLanguage.System -> "en"
            AppLanguage.English -> "en"
            AppLanguage.Arabic -> "ar"
            AppLanguage.Japanese -> "ja"
            AppLanguage.SimplifiedChinese -> "zh-CN"
            AppLanguage.Spanish -> "es"
        }

        fun isArabic(language: AppLanguage): Boolean =
            resolveLanguage(language) == AppLanguage.Arabic

        private fun systemLanguage(): AppLanguage {
            val languages = listOf(window.navigator.language) + window.navigator.languages.toList()
            return resolveLanguageTags(languages)
        }
    }
}
