package app.fukaha.android.theme

import androidx.compose.ui.graphics.Color

// Reserved for the tiny "Selected" status badge; never used as a generic theme role.
val selectedBadgeGold = Color(0xFFFFC107)
val onSelectedBadgeGold = Color(0xFF2B2100)

/*
 * Fukaha brand roles, derived from the link's dominant #5FC763 -> #018178 green gradient.
 * Its RGB midpoint is #30A46E; the vivid source colours are moved onto accessible Material 3
 * tones here. The icon's small wood and gold details stay artwork accents, not generic UI roles.
 */
val primaryLight = Color(0xFF176B49)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA4F2C8)
val onPrimaryContainerLight = Color(0xFF002112)
val secondaryLight = Color(0xFF4D6355)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCFE9D7)
val onSecondaryContainerLight = Color(0xFF0A1F14)
val tertiaryLight = Color(0xFF386A20)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB8F397)
val onTertiaryContainerLight = Color(0xFF0C2004)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF6FBF5)
val onBackgroundLight = Color(0xFF171D19)
val surfaceLight = Color(0xFFF6FBF5)
val onSurfaceLight = Color(0xFF171D19)
val surfaceVariantLight = Color(0xFFDBE5DB)
val onSurfaceVariantLight = Color(0xFF404942)
val outlineLight = Color(0xFF707970)
val outlineVariantLight = Color(0xFFBFC9BF)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C322D)
val inverseOnSurfaceLight = Color(0xFFEDF2EB)
val inversePrimaryLight = Color(0xFF88D8AD)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F5EF)
val surfaceContainerLight = Color(0xFFEAF0E9)
val surfaceContainerHighLight = Color(0xFFE4EAE3)
val surfaceContainerHighestLight = Color(0xFFDEE4DD)

val primaryDark = Color(0xFF88D8AD)
val onPrimaryDark = Color(0xFF003822)
val primaryContainerDark = Color(0xFF005233)
val onPrimaryContainerDark = Color(0xFFA4F2C8)
val secondaryDark = Color(0xFFB4CCBC)
val onSecondaryDark = Color(0xFF20352A)
val secondaryContainerDark = Color(0xFF364B40)
val onSecondaryContainerDark = Color(0xFFCFE9D7)
val tertiaryDark = Color(0xFF9CD67D)
val onTertiaryDark = Color(0xFF0F3905)
val tertiaryContainerDark = Color(0xFF22510F)
val onTertiaryContainerDark = Color(0xFFB8F397)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0F1511)
val onBackgroundDark = Color(0xFFDEE4DC)
val surfaceDark = Color(0xFF0F1511)
val onSurfaceDark = Color(0xFFDEE4DC)
val surfaceVariantDark = Color(0xFF404940)
val onSurfaceVariantDark = Color(0xFFBFC9BD)
val outlineDark = Color(0xFF89938A)
val outlineVariantDark = Color(0xFF404940)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE4DC)
val inverseOnSurfaceDark = Color(0xFF2C322D)
val inversePrimaryDark = Color(0xFF176B49)
val surfaceContainerLowestDark = Color(0xFF0A100C)
val surfaceContainerLowDark = Color(0xFF171D19)
val surfaceContainerDark = Color(0xFF1B211D)
val surfaceContainerHighDark = Color(0xFF252B27)
val surfaceContainerHighestDark = Color(0xFF303630)
